### ISSUE TITLE
yarn dev fails with Uncaught Error related to registerTldrawLibraryVersion

### ISSUE THREAD

**Issue by newtriks** [tldraw/tldraw-sync-cloudflare#2]
1. Clone repos
2. `yarn`
3. `yarn dev`

Expected:

Runs servers as documented in readme with no errors

Actual:

Errors with below output.

Note:

Tried older versions of node, no joy. I tried with version `3.0.1` and `3.0.0` with the same result, however, using version `2.4.6` of `@tldraw` libraries worked.

```
% yarn dev
yarn run v1.22.22
$ concurrently --kill-others --names client,worker --prefix-colors blue,red yarn:dev:client yarn:dev:worker
$ vite
$ wrangler dev
[client] Re-optimizing dependencies because vite config has changed
[client] 
[client]   VITE v5.4.5  ready in 1531 ms
[client] 
[client]   ➜  Local:   http://localhost:5173/
[client]   ➜  Network: use --host to expose
[worker] 
[worker]  ⛅️ wrangler 3.78.2
[worker] -------------------
[worker] 
[worker] Your worker has access to the following bindings:
[worker] - Durable Objects:
[worker]   - TLDRAW_DURABLE_OBJECT: TldrawDurableObject
[worker] - R2 Buckets:
[worker]   - TLDRAW_BUCKET: tldraw-content-preview
[worker] [wrangler:inf] Ready on http://0.0.0.0:5172
[wrangler:inf] - http://127.0.0.1:5172
[wrangler:inf] - http://192.168.86.33:5172
⎔ Starting local server...

[worker] ✘ [ERROR] service core:user:worker: Uncaught Error: Disallowed operation called within global scope. Asynchronous I/O (ex: fetch() or connect()), setting a timeout, and generating random values are not allowed within global scope. To fix this error, perform this operation within a handler. https://developers.cloudflare.com/workers/runtime-apis/handlers/
[worker] 
[worker]     at null.<anonymous> (worker.js:1612:28) in registerTldrawLibraryVersion
[worker]     at null.<anonymous> (worker.js:2757:1)
[worker] 

[worker] ✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
[worker] 

[worker] ⎔ Shutting down local server...  
```

macOS: `13.6.7 (22G720)`
node: `Node.js v20.12.2`
npm: `10.8.1`

**Comment by phgn0** [comment]
@SomeHats thank you for the fix!!

However it seems like it's not yet included in the latest tldraw release `3.0.3`. Can we please update the dependency version in this repo once the fix gets released?
